# -*- coding: utf-8 -*-
"""d3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YeDkMwTq7KhBjxKrDlM5hjO3lPfyHOfK
"""

f=open("myfile.txt","w")
print("Name of file:",f.name)
print("file mode:",f.mode)
print("readable:",f.readable())
print("writeable:",f.writable())
print("file closed:",f.closed)
f.close()
print("Name of file:",f.closed)

f=open("myfile.txt","a")
f.write("\n Nagpur is smart city")
f.close()
print("File operation is done")

#inserting list
f=open("myfile.txt","a")
mylist=["Aditya","Soham","Darshan","Vedant"]
f.write("\n")

f.writelines(mylist)
f.close()
print("File operation is done")

f=open("myfile.txt","r")
print(f.read())
f.close()

#until we are inside indendation block file is not closed
with open("myfile2.txt","w") as f:
  f.write("Aditya\n")
  f.write("Ashish\n")
  f.write("Jack\n")
  print("file closed",f.closed)
print("file closed",f.closed)

with open("myfile2.txt","r") as f:
  content=f.read()
  print(content)

f1=open("img2.jpg","rb")
f2=open("img3.jpg","wb")

data=f1.read()
f2.write(data)

import csv
f=open("student.csv","a",newline="")
a=csv.writer(f)
a.writerow(["StudentID","rollno","name","mobileno"])

import csv
f=open("student.csv","a",newline="")
a=csv.writer(f)

studentid=int(input("Enter student id:"))
rollno=int(input("Enter roll number:"))
name=input("Enter student name:")
mobileno=int(input("Enter student mobile number:"))
a.writerow([studentid,rollno,name,mobileno])
print("student record has save")

import csv
f=open("student2.csv","a",newline="")
a=csv.writer(f)
a.writerow(["rollno","name","mobileno","Emailid","p1","p2","p3","total","percentage","result"])

rollno=int(input("Enter your roll number:"))
name=input("Enter your name:")
mobileno=int(input("Enter your mobile number:"))
Emailid=input("Enter your Emailid:")
p1=int(input("Enter marks of paper1:"))
p2=int(input("Enter marks of paper1:"))
p3=int(input("Enter marks of paper1:"))

total=p1+p2+p3
percentage=(total/p1+p2+p3)*100

if p1>=40 and p2>=40 and p3>=40:
  result="pass"
else:
  result="fail"

a.writerow([rollno,name,mobileno,Emailid,p1,p2,p3,total,percentage,result])

print("work done")

# Open the file in read mode ('r')
with open('student2.csv', 'r') as file:
    content = file.read()
    print(content)

import csv

# Open the CSV file in read mode
with open('student2.csv', mode='r') as file:
    csv_reader = csv.reader(file)

    # Skip the header if there is one
    next(csv_reader)  # Uncomment this line if your file has a header

    # Iterate through the rows in the CSV file
    for row in csv_reader:
        print(row)  # Each row is a list of values

import csv

# Function to read student data based on roll number
def find_student_by_rollno(rollno_to_find):
    with open("student2.csv", "r") as f:
        csv_reader = csv.reader(f)

        # Skip the header row
        header = next(csv_reader)  # This skips the header

        # Iterate over each row to find the student with the specified roll number
        for row in csv_reader:
          rollno = int(row[0])  # Assuming roll number is in the first column
          if rollno == rollno_to_find:
            return row  # Return the entire row for the matched roll number
        return None  # Return None if roll number not found

# Input roll number to search for
rollno_to_search = int(input("Enter the roll number to search for: "))
student_data = find_student_by_rollno(rollno_to_search)

if student_data:
    print("Student data found:")
    print(f"Roll No: {student_data[0]}")
    print(f"Name: {student_data[1]}")
    print(f"Mobile No: {student_data[2]}")
    print(f"Email ID: {student_data[3]}")
    print(f"Paper 1 Marks: {student_data[4]}")
    print(f"Paper 2 Marks: {student_data[5]}")
    print(f"Paper 3 Marks: {student_data[6]}")
    print(f"Total Marks: {student_data[7]}")
    print(f"Percentage: {student_data[8]}")
    print(f"Result: {student_data[9]}")
else:
    print("Student not found.")