# -*- coding: utf-8 -*-
"""Day31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1enbBy1-hdpHZEx00vhxbgKPpdfoKO-C2
"""

s=input("Enter any string:")
s2=s.split()
rev = ' '.join(reversed(s2))
print(rev)
# print(s.split())

#set
myset={1,"Aditya","Rahul",9.2,"Soham","Akshay"}
# print(myset)
# print(myset[0])
myset.add(50)
print(myset)

#discard():-if u r not 100% sure that value is present in set

myset.discard(1)
print(myset)

#remove():-if u r   100% sure that value is present in set

myset.remove(3)
print(myset)

#union()
myset={10,20,30,40}
yorset={"prashant","jha"}
newset=myset.union(yorset)
print(newset)

#intersection
myset={10,20,30,40}
yorset={10,50, 60, 30}
print(myset.intersection(yorset))

#difference():-present in first set but not in second
myset={10,20,30,40}
yorset={10,50, 60, 30}
print(myset.difference(yorset))

#pop()
myset={10,20,30,40}
print(myset.pop())

print(myset.clear())
print(myset)

#Dictionary
mydict={
    101:"Prashant",
    102:"Aditya",
    "103":"Soham",
    "104":"Darshan",
    101:"ashish",
    104:"ashish"
}

print(mydict)

# a=mydict[102]
# print(a)

# mydict[102]="peter"
# print(mydict)

# for i in mydict:
#   print(i)

# for i in mydict.values():
#   print(i)

#items()
# for x,y in mydict.items():
#   print(x,y)

#add new key and value
# mydict["mobile no"]=1234567890
# print(mydict)

mydict2={
    101:"Aditya",
    "Profession":"developer",
    "empid":1001
}

d=mydict2.pop(101)
print(mydict2)

new=mydict2.copy()
print(new)

mydict={
    "A":10,
    "B":20,
    "C":30,
    "D":40
}

sum=0
for i in mydict.values():
  sum+=i

print(sum)

mydict={
    "C":3,
    "B":2,
    "A":1
    }

    #decending by value

mydict={
    "A":1,
    "B":2,
    "C":3
    }
mydict.clear()
print(mydict)

#non-empty values in dict

#largest value in dictionary
mydict={
    "A":10,
    "B":20,
    "C":30,
    "D":60,
    "E":50
}

max=0

for i in mydict.values():
  if i>max:
    max=i

print(max)

