# -*- coding: utf-8 -*-
"""Exception handling3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dxiwVvJAQLIF89TQcw1AAWf8QA38rMI1
"""

a=int(input('Enter first value:'))
b=int(input('Enter second value:'))

try:
  print(a/b)
except:
  print('can not devide by zero')

try:
  a=int(input('Enter first value:'))
  b=int(input('Enter second value:'))
  print(a/b)
except ZeroDivisionError as message:
  print("plz Ensure that you can not divide any number by zero",message)
except ValueError as message:
  print("Enter only integer",message)

#multiple error in same except block
try:
  a=int(input('Enter first value:'))
  b=int(input('Enter second value:'))
  print(a/b)
except (ZeroDivisionError,ValueError) as message:
  print(message)

# try:
#   a=int(input('Enter first value:'))
#   b=int(input('Enter second value:'))
#   print(a/b)
# except:
#   print("This is default except block")
# except (ZeroDivisionError,ValueError) as message:
#   print(message)

#it will go in else when error not found
try:
  a=int(input('Enter first value:'))
  b=int(input('Enter second value:'))
  print(a/b)

except (ZeroDivisionError,ValueError) as message:
  print("Enter correct number:",message)
else:
  print("Everything is ok")

try:
  a=int(input('Enter first value:'))
  b=int(input('Enter second value:'))
  print(a/b)

except (ZeroDivisionError,ValueError) as message:
  print("Enter correct number:",message)
finally:
  print("I will always executed")

try:
  a=int(input('Enter first value:'))
  b=int(input('Enter second value:'))
  try:
    print(a/b)
  except ZeroDivisionError as msg:
    print(msg)

except ValueError as msg:
  print(msg)

try:
  a=int(input('Enter first value:'))
  b=int(input('Enter second value:'))
  print(a/b)

except (ZeroDivisionError,ValueError) as message:
  print("Enter correct number:",message)

else:
  print("Therer are no error 0")
finally:
  print("I will always executed")

input_str=input("Enter any number:")
# count=0
# temp=[]
# l=list(a.split())


# for i in l:
#   if i not in temp:
#     temp.append(i)
#   else:
#     count+=1


# print(count)

# print(l)

# code = [int(input_str[i]) for i in range(len(input_str))]
code = list(map(int, input_str))
# Create blank list
temp = []
# Create counter to count repeated numbers
count = 0
for i in code:
	# Append i if element is not in temp
    if i not in temp:
        temp.append(i)
    else:
		# Count if the number is already in temp list
        count += 1
print(count)