# -*- coding: utf-8 -*-
"""Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nMh8N6sCbpdhajw7bs25NzOJsFK9Ry9U
"""

def login():
  username=input("Enter your username:")
  password=input("Enter your password:")

  if username == password:
    print("Login successfully")
  else:
    print("You entered wrong credentials")


login() #calling function

#positionam parameters
def info(firstname,lastname):
  print("First name:",firstname)
  print("Last name:",lastname)
info("Aditya","Shinde")

def arithematic(a,b):
  r=a+b
  m=a*b
  n=a-b

  return r,m,n #fixed

result=arithematic(10,5)
print(result)

#
def func(fname,lname):
  print("hi",fname)
  print("hi",lname)

func(fname="Aditya",lname="Shinde")