# -*- coding: utf-8 -*-
"""module1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TinpOvZYWUu1LG2J4Vv8QQXaJk38jQ20
"""

def welcome(fname,lname):
  print("First name",fname)
  print("last name",lname)

  def square(n):
    print(n*n)

  pi=3.145149545

  def login():
    username=input("Enter your username:")
    password=input("Enter your password:")

    if username == password:
      print("Login successfully")
    else:
      print("You entered wrong credentials")