# -*- coding: utf-8 -*-
"""module32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GuzQ1yId070Il68diYuL3n9Y6lZMD90E
"""

#import module1
#module1.square(3)

#mport module1 as mod
#mod.square(3)

#from module1 import pi,square,login
#print(pi)
#square(4)
#login('user','user')

# from module1 import *
# print(pi)
# square(4)
# login('user','user')

import module1
module1.square(3)
module1.login('user','user')

import math
print(math.sqrt(16))
print(math.pi)

#math
from math import *
print(int(sqrt(4)))
print(ceil(4.1))
print(floor(4.1))
print(fabs(-5.6))
print(fabs(4.6))

#random
from random import *
for i in range(5):
  print(random())

#randint()
from random import *
for i in range(5):
  print(randint(1,100000))

#uniform()
from random import *
for i in range(10):
  print(uniform(1,10))

#choice()
from random import *
list=["aditya","soham","darshan","Sahil"]
for i in range((5)):
  print(choice(list))

mylist=[[100,198,333,323],[122,232,221,111],[223,565,245,764]]#written max from every tuple
newlist=[]
for i in range(3):
  j=0
  max=mylist[i][j]

  for j in range(4):
    c_max=mylist[i][j]
    if max<c_max:
      max=c_max
  newlist.append(max)

print(newlist)